### ISSUE TITLE
Use mandrill to email recruitment form info

### ISSUE THREAD

**Issue by Lman95** [kjneaville/343-Final-Project#14]

**Comment by ahutch95** [comment]
https://www.codecademy.com/en/tracks/mandrill i just dont understand enough about javascript to implement it

**Comment by ahutch95** [comment]
https://www.codecademy.com/en/tracks/mandrill i just dont understand enough about javascript to implement it. only like 4 steps.

**Comment by Lman95** [comment]
Cool, I'll work on it!

**Comment by ahutch95** [comment]
i think KJ was going to just have it all send to firebase and then send an alert email when new data was added

**Comment by kjneaville** [comment]
Ok I got everything working, you can now save recruitment information
within our Firebase. I'll clean it up, add comments, then deploy it and
submit it through Canvas. We still all need to fill out group evaluations,
and lets all say we contributed equally because we can get market down for
people doing too little/too much.
