### ISSUE TITLE
Adding calendar to events page

### ISSUE THREAD

**Issue by kjneaville** [kjneaville/343-Final-Project#3]

**Comment by Lman95** [comment]
I started trying to add a calendar through calendarview, but I'm getting some errors and I'm not really sure where I should be putting the script code so that it would work well with angular and the ui router and all that. I was just going off of the site http://calendarview.org/. I tried google calendar as well and that shows up fine, it just doesn't look very nice and would probably be harder to style than calendarview, but if we end up running out of time we could probably just use Google Calendar

**Comment by Lman95** [comment]
I think the reason for the errors is that prototype and angular are made to do the same kinds of things, so they don't work well together. I found this http://angular-ui.github.io/ui-calendar/, but it allows people to move events around, which we probably don't want. With that said I think Google Calendar is gonna be the way to go. I'll make one for now as a dummy, but if the house ends up using it would be better to have one on there that the house is in control of obviously
